---
title: "MLB"
author: "YURU"
date: "2019/12/11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 連結資料庫

```{r, include=FALSE}
#set file
url <- "D:/YURU/Documents/YURU/CS/R/DataMining/"
setwd(url)
```

```{r, include=FALSE}
library(RSQLite)
library(dplyr)
```

```{r}
#connect DB
drv <- dbDriver("SQLite")
db <- dbConnect(drv, "data.db")
dbListTables(db)
```


## 球速與轉速對於揮空率之分析

### 讀取資料庫內容
從資料庫中取出球速、轉速及描述資料

```{r}
release_speed_rate <- dbGetQuery(db, "SELECT release_speed,release_spin_rate,description,launch_angle,pitch_name from mlb_record")
```

### 整理
將球速、轉速分為各項級距

```{r}
release_speed_rate[["release_speed"]] <- ordered(cut(release_speed_rate[[ "release_speed"]], c(0,70,75,80,85,90,95,100,110)),labels = c("<70", "70-75", "75-80", "80-85", "85-90", "90-95", "95-100", ">100"))

release_speed_rate[["release_spin_rate"]] <- ordered(cut(release_speed_rate[[ "release_spin_rate"]], c(0,1700,1900,2100,2300,2500,4000)),labels = c("<1700", "1700-1900", "1900-2100", "2100-2300", "2300-2500", ">2500"))
```

### 計算揮空率
將有揮擊動作之描述挑選出來，並判斷是否揮空。

```{r}
#選出有揮擊之動作
hit <- c("hit_into_play_score","hit_into_play","foul","swinging_strike","swinging_strike_blocked","hit_into_play_no_out","foul_tip")
swinging_strike <- release_speed_rate[-4]
swinging_strike$swinging_strike <- FALSE

swinging_strike[swinging_strike$description=='swinging_strike','swinging_strike'] <- TRUE
swinging_strike[swinging_strike$description=='swinging_strike_blocked','swinging_strike'] <- TRUE

swinging_strike <- na.omit(swinging_strike)
swinging_strike <- filter(swinging_strike,description %in% hit)
swinging_strike <- swinging_strike[-3]
```
計算出揮空率。
```{r}
swinging_strike_mean <- swinging_strike %>%
  group_by(release_speed,release_spin_rate) %>%
  summarise(count = n(),mean = mean(swinging_strike))
```
```{r, echo=FALSE}
swinging_strike_mean
```

### 繪製表格
將上方整理完之資料繪製表格。
```{r}
spin <- swinging_strike_mean$release_spin_rate%>%unique()
speed <- swinging_strike_mean$release_speed%>%unique()
```
```{r}
get <- function(data,speed,spin){
  d <- data%>%filter(release_speed == speed,release_spin_rate == spin)
  if(nrow(d) == 0)
    return(NA)
  else if(d$count<3)
    return(NA)
  return(d$mean)
}
```
```{r}
table_swinging_strike_mean<-lapply(spin,function(r){
  data.frame(
    spin = r,
    '<70' = get(swinging_strike_mean,"<70",r)*100,
    '70-75' = get(swinging_strike_mean,"70-75",r)*100,
    '75-80' = get(swinging_strike_mean,"75-80",r)*100,
    '80-85' = get(swinging_strike_mean,"80-85",r)*100,
    '85-90' = get(swinging_strike_mean,"85-90",r)*100,
    '90-95' = get(swinging_strike_mean,"90-95",r)*100,
    '95-100' = get(swinging_strike_mean,"95-100",r)*100,
    '>100' = get(swinging_strike_mean,">100",r)*100
  )
})%>%bind_rows()%>%t()%>%{
  colnames(.) <- spin
  .[-1,]
  }%>%apply(.,2,function(ta){
    ta%>%as.numeric%>%round(digits = 2)
  })
```
```{r, include=FALSE}
table_swinging_strike_mean <- data.frame(table_swinging_strike_mean)
colnames(table_swinging_strike_mean) <- spin
rownames(table_swinging_strike_mean) <- speed
```
```{r, echo=FALSE}
table_swinging_strike_mean
```

### 繪製熱力圖
將上方整理完之資料繪製熱力圖。
```{r, include=FALSE}
library(gplots)
```

```{r, warning=FALSE}
heatmap.2(table_swinging_strike_mean%>%as.matrix(),
          cellnote = table_swinging_strike_mean%>%as.matrix(),
          notecol="black", 
          density.info="none",
          trace="none",
          col=colorpanel(100,low="white",mid="yellow",high="red"),
          Colv = NA, Rowv = NA)
```

利用上圖看出:
大部分轉速越高揮空率越高，但球速不一定越高，這可能與球種有關，若為變化球球速會較直球慢但揮空率較高。

## 加入球種探討

### 快速球 vs 變化球

```{r}
Fastball <- c("4-Seam Fastball","2-Seam Fastball")
Breakingball <- c("Slider","Changeup","Curveball","Forkball","Split Finger","Cutter","Knuckle Ball","Knuckle Curve")

swinging_strike_Fastball <- filter(swinging_strike,pitch_name %in% Fastball)
swinging_strike_Breakingball <- filter(swinging_strike,pitch_name %in% Breakingball)
```
計算出揮空率。
```{r}
swinging_strike_Fastball_mean <- swinging_strike_Fastball %>%
  group_by(release_speed,release_spin_rate) %>%
  summarise(count = n(),mean = mean(swinging_strike))

swinging_strike_Breakingball_mean <- swinging_strike_Breakingball %>%
  group_by(release_speed,release_spin_rate) %>%
  summarise(count = n(),mean = mean(swinging_strike))
```
```{r, include=FALSE}
swinging_strike_Fastball_mean <- data.frame(swinging_strike_Fastball_mean)
swinging_strike_Breakingball_mean <- data.frame(swinging_strike_Breakingball_mean)
```

### 繪製表格
快速球  
```{r}
table_swinging_Fastball_mean<-lapply(spin,function(r){
  data.frame(
    spin = r,
    '<70' = get(swinging_strike_Fastball_mean,"<70",r)*100,
    '70-75' = get(swinging_strike_Fastball_mean,"70-75",r)*100,
    '75-80' = get(swinging_strike_Fastball_mean,"75-80",r)*100,
    '80-85' = get(swinging_strike_Fastball_mean,"80-85",r)*100,
    '85-90' = get(swinging_strike_Fastball_mean,"85-90",r)*100,
    '90-95' = get(swinging_strike_Fastball_mean,"90-95",r)*100,
    '95-100' = get(swinging_strike_Fastball_mean,"95-100",r)*100,
    '>100' = get(swinging_strike_Fastball_mean,">100",r)*100
  )
})%>%bind_rows()%>%t()%>%{
  colnames(.) <- spin
  .[-1,]
  }%>%apply(.,2,function(ta){
    ta%>%as.numeric%>%round(digits = 2)
  })
```
```{r, include=FALSE}
table_swinging_Fastball_mean <- data.frame(table_swinging_Fastball_mean)
colnames(table_swinging_Fastball_mean) <- spin
rownames(table_swinging_Fastball_mean) <- speed
```
```{r, echo=FALSE}
table_swinging_Fastball_mean
```
變化球  
```{r}
table_swinging_Breakingball_mean<-lapply(spin,function(r){
  data.frame(
    spin = r,
    '<70' = get(swinging_strike_Breakingball_mean,"<70",r)*100,
    '70-75' = get(swinging_strike_Breakingball_mean,"70-75",r)*100,
    '75-80' = get(swinging_strike_Breakingball_mean,"75-80",r)*100,
    '80-85' = get(swinging_strike_Breakingball_mean,"80-85",r)*100,
    '85-90' = get(swinging_strike_Breakingball_mean,"85-90",r)*100,
    '90-95' = get(swinging_strike_Breakingball_mean,"90-95",r)*100,
    '95-100' = get(swinging_strike_Breakingball_mean,"95-100",r)*100,
    '>100' = get(swinging_strike_Breakingball_mean,">100",r)*100
  )
})%>%bind_rows()%>%t()%>%{
  colnames(.) <- spin
  .[-1,]
  }%>%apply(.,2,function(ta){
    ta%>%as.numeric%>%round(digits = 2)
  })
```
```{r, include=FALSE}
table_swinging_Breakingball_mean <- data.frame(table_swinging_Breakingball_mean)
colnames(table_swinging_Breakingball_mean) <- spin
rownames(table_swinging_Breakingball_mean) <- speed
```
```{r, echo=FALSE}
table_swinging_Breakingball_mean
```


### 繪製熱力圖
快速球  
```{r, echo=FALSE, warning=FALSE}
heatmap.2(table_swinging_Fastball_mean%>%as.matrix(),
          cellnote = table_swinging_Fastball_mean%>%as.matrix(),
          notecol="black", 
          density.info="none",
          trace="none",
          col=colorpanel(100,low="white",mid="yellow",high="red"),
          Colv = NA, Rowv = NA)
```
  
變化球  
```{r, echo=FALSE, warning=FALSE}
heatmap.2(table_swinging_Breakingball_mean%>%as.matrix(),
          cellnote = table_swinging_Breakingball_mean%>%as.matrix(),
          notecol="black", 
          density.info="none",
          trace="none",
          col=colorpanel(100,low="white",mid="yellow",high="red"),
          Colv = NA, Rowv = NA)
```

由圖可發現，快速球對於揮空率轉速與球速越高，則揮空率也越大。  
而變化球則是速度越慢，轉速介於1900到2100之間揮空率最高。


## 球速與轉速對於打擊角度之分析

```{r}
launch_angle <- release_speed_rate[-3]
launch_angle <- na.omit(launch_angle)
```
```{r}
launch_angle_mean <- launch_angle %>%
  group_by(release_speed,release_spin_rate) %>%
  summarise(count = n(),mean = mean(launch_angle))
```

### 繪製表格

```{r}
table_launch_angle_mean<-lapply(spin,function(r){
  data.frame(
    spin = r,
    '<70' = get(launch_angle_mean,"<70",r),
    '70-75' = get(launch_angle_mean,"70-75",r),
    '75-80' = get(launch_angle_mean,"75-80",r),
    '80-85' = get(launch_angle_mean,"80-85",r),
    '85-90' = get(launch_angle_mean,"85-90",r),
    '90-95' = get(launch_angle_mean,"90-95",r),
    '95-100' = get(launch_angle_mean,"95-100",r),
    '>100' = get(launch_angle_mean,">100",r)
  )
})%>%bind_rows()%>%t()%>%{
  colnames(.) <- spin
  .[-1,]
  }%>%apply(.,2,function(ta){
    ta%>%as.numeric%>%round(digits = 2)
  })
```
```{r, include=FALSE}
table_launch_angle_mean <- data.frame(table_launch_angle_mean)
colnames(table_launch_angle_mean) <- spin
rownames(table_launch_angle_mean) <- speed
```
```{r, echo=FALSE}
table_launch_angle_mean
```

### 繪製熱力圖

```{r, warning=FALSE}
heatmap.2(table_launch_angle_mean%>%as.matrix(),
          cellnote = table_launch_angle_mean%>%as.matrix(),
          notecol="black", 
          density.info="none",
          trace="none",
          col=colorpanel(100,low="white",mid="white" ,high="steelblue"),
          Colv = NA, Rowv = NA)
```

滾地球 : <10 度  
平飛球 : 10-25 度  
高飛球 : 25-50 度  
內野高飛 : >50 度


